=== newtimestube/XML/Exercicis DTD/Act4.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT CatalegPelicules (Pelicula+)>
<!ELEMENT Pelicula (Titol, Durada, Genere, Actors, Any, Director, Format?)>
<!ELEMENT Titol (#PCDATA)>
<!ELEMENT Durada (#PCDATA)>
<!ELEMENT Genere (#PCDATA)>
<!ELEMENT Actors (Actor+)>
<!ELEMENT Actor (#PCDATA)>
<!ELEMENT Any (#PCDATA)>
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Format (#PCDATA)>

=== newtimestube/XML/Exercicis DTD/pelicules.xml
<?xml version="1.0"?>
<!DOCTYPE CatalegPelicules SYSTEM "Act4.dtd">
<CatalegPelicules>
    <Pelicula>
        <Titol>The Matrix</Titol>
        <Durada>136</Durada>
        <Genere>Science Fiction</Genere>
        <Actors>
            <Actor>Keanu Reeves</Actor>
            <Actor>Laurence Fishburne</Actor>
            <Actor>Carrie Ann Moss</Actor>
        </Actors>
        <Any>1999</Any>
        <Director>Wachowski Brothers</Director>
        <Format>DVD</Format>
    </Pelicula>
    <Pelicula>
        <Titol>Titanic</Titol>
        <Durada>194</Durada>
        <Genere>Drama</Genere>
        <Actors>
            <Actor>Leonardo DiCaprio</Actor>
            <Actor>Kate Winslet</Actor>
        </Actors>
        <Any>1999</Any>
        <Director>James Cameron</Director>
        <Format>DVD</Format>
    </Pelicula>
    <Pelicula>
        <Titol>The Sixth Sense</Titol>
        <Durada>106</Durada>
        <Genere>Thriller</Genere>
        <Actors>
            <Actor>Bruce Willis</Actor>
            <Actor>Haley Joel Osment</Actor>
        </Actors>
        <Any>1999</Any>
        <Director>M. Night Shyamalan</Director>
    </Pelicula>
</CatalegPelicules>
