=== newtimestube/XML/Exercicis DTD/Act5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Jocs_Olimpics (Olimpiada)>
<!ELEMENT Olimpiada (Pais, Dates, Caracteristiques)>
<!ELEMENT Pais (Ciutat)>
<!ELEMENT Ciutat (#PCDATA)>
<!ELEMENT Dates (Inici, Fi)>
<!ELEMENT Inici (#PCDATA)>
<!ELEMENT Fi (#PCDATA)>
<!ELEMENT Caracteristiques (Inauguracio, Participants)>
<!ELEMENT Inauguracio (#PCDATA)>
<!ELEMENT Participants EMPTY>
<!ATTLIST Olimpiada Any CDATA #REQUIRED>
<!ATTLIST Pais Nom CDATA #REQUIRED>
<!ATTLIST Caracteristiques Nom_oficial CDATA #IMPLIED>
<!ATTLIST Participants Comites CDATA #REQUIRED>
<!ATTLIST Participants Atletes CDATA #REQUIRED>

=== newtimestube/XML/Exercicis DTD/Act5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Jocs_Olimpics SYSTEM "Act5.dtd">

<Jocs_Olimpics> 
    <Olimpiada Any="2012">
        <Pais Nom="Regne Unit">
            <Ciutat>Londres</Ciutat>
        </Pais>
        <Dates>
            <Inici>27 de juliol de 2012</Inici>
            <Fi>12 d'agost de 2012</Fi>
        </Dates>
        <Caracteristiques Nom_oficial="Jocs de la XXX Olimpiada">
            <Inauguracio>Elisabet II</Inauguracio>
            <Participants Comites="204" Atletes ="10.820"/>
        </Caracteristiques>
    </Olimpiada>
</Jocs_Olimpics>
