=== newtimestube/XML/Exercicis DTD/receptes.dtd
<!ELEMENT recepte (ingredient+)>
<!ELEMENT ingredient (nomingredient,quantitat,obs?)>
<!ELEMENT nomingredient (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT obs (#PCDATA)>
<!ATTLIST recepte nom CDATA #REQUIRED tipus (ENTRANT|PRINCIPAL|POSTRE) #IMPLIED>
<!ATTLIST quantitat mesura CDATA #REQUIRED>

=== newtimestube/XML/Exercicis DTD/Act3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recepte SYSTEM "receptes.dtd">

<recepte nom="Crepes">
    <ingredient>
        <nomingredient>ou</nomingredient>
        <quantitat mesura="unitats">2</quantitat>
        <obs>Ninguna</obs>
    </ingredient>
    <ingredient>
        <nomingredient>farina</nomingredient>
        <quantitat mesura="grams">250g</quantitat>
        <obs>Utilitzar la de la empresa maggie</obs>
    </ingredient>
    <ingredient>
        <nomingredient>llet</nomingredient>
        <quantitat mesura="ml">100ml</quantitat>
        <obs>Ninguna</obs>
    </ingredient>
</recepte>
